# Generated by Django 4.2.7 on 2023-12-27 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASKII', '0002_alter_question_managers_alter_questionlike_question'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='answerlike',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='question',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='questionlike',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ASKII.question'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/Images'),
        ),
    ]
