# Generated by Django 4.2.7 on 2024-01-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASKII', '0005_alter_answerlike_answer_alter_question_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='Hombre.png', null=True, upload_to='avatar/'),
        ),
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('author', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('author', 'question')},
        ),
    ]
